[package]
name = "gui_default_animator_f64_quadratic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uianimator = { path = "../../" }
speedy2d = "2.1.0"
